USE [master]
GO

/****** Object:  Table [dbo].[Elektricar]    Script Date: 6/15/2022 10:52:39 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Elektricar](
	[JMBG] [int] NOT NULL,
 CONSTRAINT [PK_ELEKTRICAR] PRIMARY KEY CLUSTERED 
(
	[JMBG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Elektricar]  WITH CHECK ADD  CONSTRAINT [Elektricar_fk0] FOREIGN KEY([JMBG])
REFERENCES [dbo].[Radnik] ([JMBG])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Elektricar] CHECK CONSTRAINT [Elektricar_fk0]
GO


