USE [master]
GO

/****** Object:  Table [dbo].[Potrosac]    Script Date: 6/15/2022 10:54:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Potrosac](
	[POT_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAZIV] [varchar](255) NOT NULL,
	[SIFRA] [varchar](500) NOT NULL,
 CONSTRAINT [PK_POTROSAC] PRIMARY KEY CLUSTERED 
(
	[POT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Potrosac__A371AEE08CF8CE07] UNIQUE NONCLUSTERED 
(
	[NAZIV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


