USE [master]
GO

/****** Object:  Table [dbo].[Racun]    Script Date: 6/15/2022 10:54:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Racun](
	[BROJ_RACUNA] [int] IDENTITY(1,1) NOT NULL,
	[STRUJOMER_BROJ] [int] NOT NULL,
	[POTROSAC] [int] NOT NULL,
	[DATUM] [datetime] NOT NULL,
	[IZNOS] [decimal](18, 0) NOT NULL,
	[KWH] [decimal](18, 0) NOT NULL,
	[PERIOD] [int] NOT NULL,
 CONSTRAINT [PK_RACUN] PRIMARY KEY CLUSTERED 
(
	[BROJ_RACUNA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Racun]  WITH CHECK ADD  CONSTRAINT [FK_Racun_Potrosac] FOREIGN KEY([POTROSAC])
REFERENCES [dbo].[Potrosac] ([POT_ID])
GO

ALTER TABLE [dbo].[Racun] CHECK CONSTRAINT [FK_Racun_Potrosac]
GO

ALTER TABLE [dbo].[Racun]  WITH CHECK ADD  CONSTRAINT [FK_Racun_Strujomer] FOREIGN KEY([STRUJOMER_BROJ])
REFERENCES [dbo].[Strujomer] ([BROJ])
GO

ALTER TABLE [dbo].[Racun] CHECK CONSTRAINT [FK_Racun_Strujomer]
GO


