USE [master]
GO

/****** Object:  Table [dbo].[Ocitavanje]    Script Date: 6/15/2022 10:53:16 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Ocitavanje](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATUM] [datetime] NOT NULL,
	[KWH] [decimal](18, 0) NOT NULL,
	[STRUJOMER] [int] NOT NULL,
	[ELEKTRICAR] [int] NULL,
	[PERIOD] [int] NOT NULL,
 CONSTRAINT [PK_OCITAVANJE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Ocitavanje]  WITH CHECK ADD  CONSTRAINT [Ocitavanje_fk0] FOREIGN KEY([STRUJOMER])
REFERENCES [dbo].[Strujomer] ([BROJ])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Ocitavanje] CHECK CONSTRAINT [Ocitavanje_fk0]
GO

ALTER TABLE [dbo].[Ocitavanje]  WITH CHECK ADD  CONSTRAINT [Ocitavanje_fk1] FOREIGN KEY([ELEKTRICAR])
REFERENCES [dbo].[Elektricar] ([JMBG])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Ocitavanje] CHECK CONSTRAINT [Ocitavanje_fk1]
GO


