USE [master]
GO

/****** Object:  Table [dbo].[Odsustvo]    Script Date: 6/15/2022 10:54:05 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Odsustvo](
	[ODS_ID] [int] IDENTITY(1,1) NOT NULL,
	[RADNIK_JMBG] [int] NOT NULL,
	[DATUM_OD] [datetime] NOT NULL,
	[DATUM_DO] [datetime] NOT NULL,
	[PLACENO] [int] NOT NULL,
	[RAZLOG] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ODSUSTVO] PRIMARY KEY CLUSTERED 
(
	[ODS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Odsustvo]  WITH CHECK ADD  CONSTRAINT [Odsustvo_fk0] FOREIGN KEY([RADNIK_JMBG])
REFERENCES [dbo].[Radnik] ([JMBG])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Odsustvo] CHECK CONSTRAINT [Odsustvo_fk0]
GO


