USE [master]
GO

/****** Object:  Table [dbo].[Oprema]    Script Date: 6/15/2022 10:54:21 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Oprema](
	[OPR_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAZIV] [varchar](255) NOT NULL,
	[OPIS] [varchar](255) NOT NULL,
	[DATUM_ZADUZIVANJA] [datetime] NULL,
	[ZADUZIO] [int] NULL,
 CONSTRAINT [PK_OPREMA] PRIMARY KEY CLUSTERED 
(
	[OPR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Oprema]  WITH CHECK ADD  CONSTRAINT [FK_Oprema_Radnik] FOREIGN KEY([ZADUZIO])
REFERENCES [dbo].[Radnik] ([JMBG])
GO

ALTER TABLE [dbo].[Oprema] CHECK CONSTRAINT [FK_Oprema_Radnik]
GO


