USE [master]
GO

/****** Object:  Table [dbo].[Radnik]    Script Date: 6/15/2022 10:54:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Radnik](
	[JMBG] [int] IDENTITY(1,1) NOT NULL,
	[DATUM_RODJ] [datetime] NOT NULL,
	[IME] [varchar](255) NOT NULL,
	[PLATA] [int] NOT NULL,
	[RADNO_MESTO] [varchar](255) NOT NULL,
 CONSTRAINT [PK_RADNIK] PRIMARY KEY CLUSTERED 
(
	[JMBG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


